#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(picom ksuperkey mpd xfce-polkit xfce4-power-manager)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		killall -8 ${_prs}
	fi
done

# polkit agent
/usr/lib/xfce-polkit/xfce-polkit &

# Enable power management
xfce4-power-manager &

# # Enable Super Keys For Menu
# ksuperkey -e 'Super_L=Alt_L|F2' &
# ksuperkey -e 'Super_R=Alt_L|F2' &

# Restore wallpaper
nitrogen --restore &

exec polybar bar -c ~/.config/polybar/config &

exec picom &

exec mpd &

exec sxhkd -c ~/.config/worm/sxhkdrc &

wormc border-width 6
wormc active-border-pixel $((16$(sed -n '4p' .cache/wal/colors)))
wormc inactive-border-pixel $((16$(sed -n '5p' .cache/wal/colors)))
wormc background-pixel $((16$(sed -n '6p' .cache/wal/colors)))
wormc title-height 0

xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "Synaptics Tap Action" 0, 0, 0, 0, 1, 3, 2

exec pipewire &
startup &
