#!/usr/bin/env bash

## Autostart Programs

# Kill already running process
_ps=(mpd clash polybar sxhkd)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		pkill -8 ${_prs}
	fi
done

# Restore wallpaper
exec nitrogen --restore &

exec polybar bar -q -c ~/.config/worm/polybar/config &

# exec picom &

exec mpd &

exec sxhkd -c ~/.config/worm/sxhkdrc &

wormc border-width 6
wormc active-border-pixel $((16$(sed -n '4p' .cache/wal/colors)))
wormc inactive-border-pixel $((16$(sed -n '5p' .cache/wal/colors)))
wormc background-pixel $((16$(sed -n '6p' .cache/wal/colors)))
wormc title-height 0

exec xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "Synaptics Tap Action" 0, 0, 0, 0, 1, 3, 2 &

startup &
