#!/usr/bin/env bash

xrdb ~/.Xresources

_ps=(mpd polybar sxhkd)
for _prs in "${_ps[@]}"; do
	if [[ `pidof ${_prs}` ]]; then
		pkill -8 ${_prs}
	fi
done

exec nitrogen --restore &

exec polybar top -q -c ~/.config/worm/polybar/config.ini &

exec mpd &

exec sxhkd -c ~/.config/worm/sxhkdrc &

wormc border-width 6
wormc border-active-pixel $((16$(sed -n '4p' ~/.cache/wal/colors)))
wormc border-inactive-pixel $((16$(sed -n '5p' ~/.cache/wal/colors)))
wormc layout tiling
wormc struts 75 20 20 20
wormc gaps 20
wormc frame-height 0

exec xinput set-prop "SYNA1D31:00 06CB:CD48 Touchpad" "Synaptics Tap Action" 0, 0, 0, 0, 1, 3, 2 &

startup &
